// export const colorsLight ={
//   primaryColor: '#7835FF',
//   secondaryColor: '#05000f',
//   tertiaryColor: '#6d5a75',
//   lightPrimaryColor: '#894eff',
//   whitTextColor: '#fff',
//   primaryTextColor: '#7835FF',
//   secondaryTextColor: '#1a004f',
//   tertiaryTextColor: '#6d5a75',
//   backGroundColor: '#fefefe',
//   secondaryBackGroundColor: '#fff',
//   greyBackground: '#F5F5F5',
//   lightBackground: '#f4eafe',
//   secondaryPurple: '#8e7dc4',
// }
